### ISSUE TITLE
I installed it in Paw 2.2.2, but nowhere I can find it.

### ISSUE THREAD

**Issue by phoenixg** [luckymarmot/Paw-RAMLGenerator#1]

**Comment by JonathanMontane** [comment]
The minimum app version for the RAML Generator is Paw 3.0, as it uses javascript features that did not exists / were not exposed in previous version of Paw.

If you are not on Mavericks, I invite you to migrate to Paw 3, it's free and you will be able to use plenty of new features that should make your work more efficient.
